# Generated by Django 4.0.3 on 2023-06-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_user_id_mymodel_cameria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notfication', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
