# Generated by Django 4.0.3 on 2023-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_notfication_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='notfication',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
