# Generated by Django 4.0.3 on 2023-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification_delete_notfication_mymodel_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
