# Generated by Django 4.0.3 on 2023-06-15 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MModel',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='event_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notfication',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='notfic', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
