# Generated by Django 4.0.3 on 2023-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_mmodel_remove_mymodel_is_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notfication',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(default='4', max_length=100),
            preserve_default=False,
        ),
    ]
