# Generated by Django 4.0.3 on 2023-06-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notificat_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MModel',
        ),
    ]
