# Generated by Django 4.0.3 on 2023-06-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_mmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='is_seen',
            new_name='alarm_seen',
        ),
        migrations.DeleteModel(
            name='Notificat',
        ),
    ]
