# Generated by Django 4.0.3 on 2023-06-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_mmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='alrm_date',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notificat',
        ),
    ]
