# Generated by Django 4.0.3 on 2023-06-17 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_mymodel_alarm_seen_mymodel_alrm_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarmat', models.CharField(max_length=80)),
                ('image_ur', models.ImageField(blank=True, null=True, upload_to='my_picter')),
                ('alrm_in', models.DateTimeField(auto_now_add=True)),
                ('cameria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listigs', to='api.camira')),
            ],
        ),
    ]
