# Generated by Django 4.0.3 on 2023-06-17 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='cameria_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.camira'),
        ),
    ]
