# Generated by Django 4.0.3 on 2023-06-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_mymodel_cameria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='cameria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listigs', to='api.camira'),
        ),
    ]
