# Generated by Django 4.0.3 on 2023-06-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_alarm_cameria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='alrm_in',
            field=models.DateTimeField(),
        ),
    ]
